### ISSUE TITLE
Testset request

### ISSUE THREAD

**Issue by shleecs** [cocoakang/photometric_feature_transformer#1]
Hi, nice work!

I have some questions about this repository.

I cannot download the testing data(fox, teacup, cat, chicken) due to a problem with allyudrive.

If you don't mind, would you release another download based on google drive or dropbox?

I will be looking forward to your reply.:)

**Comment by cocoakang** [comment]
Hi shleecs!
Thanks for your interest in our project.
I will give an alternative way for downloading asap.

**Comment by cocoakang** [comment]
Hi shleecs!
I uploaded the data to oneDrive [here](https://zjueducn-my.sharepoint.com/:f:/g/personal/cocoa_kang_zju_edu_cn/EvkpIm9MpQ9Lvq6r-WWQxcUBT-Yrnb8wjlAzHnvIlSATAw?e=VCdyje). Would you check if this works?
If it still doesn't work, please notify me and I will find a way to upload them to google drive. 🙂
@shleecs

**Comment by shleecs** [comment]
It works!

Thank you for your help:)
